require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - config.ru
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - node_modules/**/*
    - Rakefile

  TargetRubyVersion: 3.0.2

RSpec/NestedGroups:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - db/migrate/**/*.rb
