default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'developer' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'developer' } %>
  host: localhost
  port: <%= ENV.fetch("POSTGRES_PORT") { '5432' } %>

development:
  <<: *default
  database: machik_development
test:
  <<: *default
  database: machik_test
production:
  <<: *default
  database: machik_production
  url: <%= ENV['DATABASE_URL'] %>
